// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw_jsdPCw4zYVs9SVKj_V0S8yA88dZ7SE',
    appId: '1:1035793599455:web:999edd3e2c10af157b126a',
    messagingSenderId: '1035793599455',
    projectId: 'cryptoapp-a71a5',
    authDomain: 'cryptoapp-a71a5.firebaseapp.com',
    storageBucket: 'cryptoapp-a71a5.appspot.com',
    measurementId: 'G-E99FTKLEGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDxQCqMY4GhiEOHk7mqE_fJ3J1cL7Abw0',
    appId: '1:1035793599455:android:0cb16665397210887b126a',
    messagingSenderId: '1035793599455',
    projectId: 'cryptoapp-a71a5',
    storageBucket: 'cryptoapp-a71a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88HTIT-ectBavipT0mCTSqcbf39Gbp7Q',
    appId: '1:1035793599455:ios:81c4febc790208667b126a',
    messagingSenderId: '1035793599455',
    projectId: 'cryptoapp-a71a5',
    storageBucket: 'cryptoapp-a71a5.appspot.com',
    iosBundleId: 'com.example.foxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88HTIT-ectBavipT0mCTSqcbf39Gbp7Q',
    appId: '1:1035793599455:ios:81c4febc790208667b126a',
    messagingSenderId: '1035793599455',
    projectId: 'cryptoapp-a71a5',
    storageBucket: 'cryptoapp-a71a5.appspot.com',
    iosBundleId: 'com.example.foxApp',
  );
}
